### ISSUE TITLE
The committed file did not fail when it should have to

### ISSUE THREAD

**Issue by MDaskalovAtBE** [rtCamp/action-phpcs-code-review#24]
When I've committed the 
```
<?php

$something = array(
    'foo' => 'bar',
    'foob'   => 'ar'
);

echo $something;


```

I was expecting ` 8 | ERROR | [x] Expected 1 blank line at end of file; 2 found`
`OK! (Files: 13578, Success: 13578)` was returned

yml -
```
name: PHP Code Sniffer

on: pull_request

jobs:
 phpcs:

   runs-on: ubuntu-18.04

   steps:
   - uses: actions/checkout@v2
     with:
       ref: ${{ github.event.pull_request.head.sha }}
   - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
     env:
       GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
     with:
       args: "PSR12"
```
