### ISSUE TITLE
PHPCS runs on PR diff instead of project?

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [rtCamp/action-phpcs-code-review#26]
When using this action yml file:
```yml
name: Test
on: pull_request
jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: docker://rtcamp/action-phpcs-code-review:v2.0.0
        env:
          GH_BOT_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

```
According to your readme phpcs is run only on the files in the pull request diff, is it also possible to run it on the entire code base? Can you maybe add a flag or so for this? :smiley:
