### ISSUE TITLE
phpcs.xml exclusion patterns being ignored

### ISSUE THREAD

**Issue by NickGreen** [rtCamp/action-phpcs-code-review#47]
## Problem

When we set `<exclude-pattern>` in the phpcs.xml file, those are being ignored, and the specified folders are being scanned anyway.

## Desired behavior

The exclusions in the phpcs.xml file should be honored, and the specified folders should be ignored during sniffing.  For example, here's one of our phpcs.xml files:

```
<?xml version="1.0"?>
<ruleset name="">
	<description>PHPCS declaration</description>

	<rule ref="WordPress-Extra">
		<exclude name="WordPress.Files.FileName.NotHyphenatedLowercase" />
		<exclude name="WordPress.Files.FileName.InvalidClassFileName" />
	</rule>

	<arg name="extensions" value="php"/>
	<arg value="s"/>

	<exclude-pattern>.github/</exclude-pattern>
	<!-- Third-party code -->
	<exclude-pattern>themes/storefront/*</exclude-pattern>
	<exclude-pattern>*/bower-components/*</exclude-pattern>
	<exclude-pattern>*/node_modules/*</exclude-pattern>
	<exclude-pattern>themes/resonar-wpcom/*</exclude-pattern>
	<exclude-pattern>themes/storefront/*</exclude-pattern>
	<exclude-pattern>*/plugins/*</exclude-pattern>
	<exclude-pattern>*/mu-plugins/*</exclude-pattern>
	<exclude-pattern>*/vendor/*</exclude-pattern>
</ruleset>
```

**In this case, the plugins folder should not be sniffed. However, it is still getting sniffed.**

## Workaround

We've added the plugins folder to the SKIP_FOLDERS setting in the action itself, e.g.:
```
on: pull_request
name: Code tests
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@master
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        SKIP_FOLDERS: "tests,.github,plugins,mu-plugins"
      with:
        args: "WordPress-Extra"
```
