### ISSUE TITLE
Possible to use GitHub App Token?

### ISSUE THREAD

**Issue by jjICP** [rtCamp/action-phpcs-code-review#65]
We implemented a GitHub app for a more secure token and then we use

```
    - name: Get GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@v3
      env:
        GH_BOT_TOKEN: ${{ steps.app-token.outputs.token }}
     ....

```
But it throws the error when running PHPCS:

```
[ 2025-06-09T21:26:55+00:00 GMT -- 0 ]  "Trying to get information about the user the GitHub-token belongs to"; []
[ 2025-06-09T21:26:55+00:00 GMT -- 0 ]  "Unable to get information about token-holder user from GitHub"; []
```

because [GitHub App tokens do not identify a user](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#get-a-user-installation-for-the-authenticated-app).  It is possible to get this updated to be able to use GitHub app tokens? Possibly skipping the user check if it's an app token or something?
